### ISSUE TITLE
Support Yarn

### ISSUE THREAD

**Issue by JohnCampionJr** [DevExpress/devextreme-cli#128]
# Feature request

 **Package versions you currently use:**

     devextreme-cli version: 1.1.10

 **Description:**
Currently the theme-builder has a hard-coded requirement for package-lock.json, blocking its use with Yarn.  It does work but it always downloads the most recent theme-builder.

 **Preferred Solution:**
To check the yarn.lock if it exists rather than package-lock.json

**Comment by JohnCampionJr** [comment]
I see there is some work around this recently, so it appears its being worked on.

**Comment by babich-a** [comment]
Hi @JohnCampionJr 
We have plans to support yarn in devextreme-cli. It is possible to use the [`--version` option](https://js.devexpress.com/Documentation/Guide/Getting_Started/DevExtreme_CLI/#ThemeBuilder/Command-Line_Arguments) now for ThemeBuilder commands.

**Comment by LexDX** [comment]
We implemented this feature in version 1.2.0. Please check this PR for more information: https://github.com/DevExpress/devextreme-cli/pull/166
