### ISSUE TITLE
Error on build themes over Devextreme version 20.2.1-alpha-20195-1008

### ISSUE THREAD

**Issue by lucasfr2cad** [DevExpress/devextreme-cli#223]
devextreme build

The DevExtreme build started
Using version 20.2.1-alpha-20195-1008.
material orange-light
Using version 20.2.1-alpha-20195-1008.
material orange-dark
Using version 20.2.1-alpha-20195-1008.
material orange-light
Using version 20.2.1-alpha-20195-1008.
material orange-dark
TypeError: baseParametersList.indexOf is not a function

///
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Fogaça\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build-themes'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [ 'prebuild-themes', 'build-themes', 'postbuild-themes' ]
5 info lifecycle otimizador@0.1.0~prebuild-themes: otimizador@0.1.0
6 info lifecycle otimizador@0.1.0~build-themes: otimizador@0.1.0
7 verbose lifecycle otimizador@0.1.0~build-themes: unsafe-perm in lifecycle true
8 verbose lifecycle otimizador@0.1.0~build-themes: PATH: C:\Users\Fogaça\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Fogaça\Documents\otimizador\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python27\;C:\Python27\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\ProgramData\chocolatey\bin;C:\Users\Fogaça\.dotnet\tools;C:\Users\Foga?a\.dotnet\tools;$Fogaça\.dotnet\tools;C:\Users\Fogaça\AppData\Roaming;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Users\Fogaça\AppData\Roaming\npm\node_modules\bower;C:\Program Files\Git\cmd;C:\Users\Fogaça\AppData\Roaming\npm\node_modules\@angular\cli;C:\Users\Fogaça\AppData\Roaming\npm;C:\Users\Foga?a\AppData\Roaming\npm\node_modules\devextreme-cli;C:\Users\Fogaça\AppData\Roaming\npm\node_modules\devextreme-cli;C:\Users\Fogaça\AppData\Roaming\npm\node_modules\pm2;C:\Users\Fogaça\AppData\Roaming\npm\node_modules\pm2-windows-startup;C:\Program Files\Java\jdk1.8.0_231\bin;C:\SDK\ANDROID_HOME\platform-tools;C:\SDK\ANDROID_HOME\tools;C:\Program Files (x86)\dotnet\;C:\Program Files (x86)\Griaule\Fingerprint SDK 2009\bin;C:\Program Files (x86)\Yarn\bin\;C;C:\Program Files\nodejs\;C:\Users\Foga?a\AppData\Local\Programs\Python\Python38-32\Scripts\;C:\Users\Foga?a\AppData\Local\Programs\Python\Python38-32\;C:\Users\Foga?a\AppData\Roaming\npm;C:\Program Files\heroku\bin;C:\Users\Foga?a\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Foga?a\AppData\Roaming\npm\node_modules\bower;C:\Users\Foga?a\AppData\Roaming\npm\node_modules\@angular\cli\bin;C:\Users\Fogaça\AppData\Roaming\npm;C:\Users\Foga?a\AppData\Roaming\npm\node_modules\pm2;C:\Users\Foga?a\AppData\Roaming\npm\node_modules\pm2-windows-startup;C:\Users\Foga?a\AppData\Local\hyper\app-3.0.2\resources\bin;C:\Users\Foga?a\AppData\Local\Programs\Fiddler;C:\Program Files\JetBrains\DataGrip 2019.3.2\bin;C:\Users\Foga?a\AppData\Roaming\npm\node_modules\@angular\cli;C:\Users\Foga�a\AppData\Local\hyper\app-3.0.2\resources\bin;C:\Users\Foga�a\AppData\Local\Yarn\bin;C:\Users\Fogaça\AppData\Local\hyper\app-3.0.2\resources\bin;C:\Users\Fogaça\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Fogaça\AppData\Local\Microsoft\WindowsApps;C:\Users\Fogaça\AppData\Roaming\npm
9 verbose lifecycle otimizador@0.1.0~build-themes: CWD: C:\Users\Fogaça\Documents\otimizador
10 silly lifecycle otimizador@0.1.0~build-themes: Args: [ '/d /s /c', 'devextreme build' ]
11 silly lifecycle otimizador@0.1.0~build-themes: Returned: code: 1  signal: null
12 info lifecycle otimizador@0.1.0~build-themes: Failed to exec build-themes script
13 verbose stack Error: otimizador@0.1.0 build-themes: `devextreme build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Fogaça\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Fogaça\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid otimizador@0.1.0
15 verbose cwd C:\Users\Fogaça\Documents\otimizador
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Fogaça\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build-themes"
18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error otimizador@0.1.0 build-themes: `devextreme build`
22 error Exit status 1
23 error Failed at the otimizador@0.1.0 build-themes script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by babich-a** [comment]
@lucasfr2cad what version of the `devextreme-cli` package do you use?

**Comment by lucasfr2cad** [comment]
devextreme-cli 1.2.1

**Comment by lucasfr2cad** [comment]
> @lucasfr2cad what version of the `devextreme-cli` package and the application type (angular, react, vue) do you use?

"devDependencies": {
    "devextreme-cli": "1.2.1",
    "devextreme-themebuilder": "20.1-stable"
  }

**Comment by lucasfr2cad** [comment]
> @lucasfr2cad what version of the `devextreme-cli` package and the application type (angular, react, vue) do you use?

I'm using a Create a DevExtreme Application (REACT)

`{
  "name": "desenho",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "devextreme": "20.2.1-alpha-20195-1008",
    "devextreme-react": "^20.2.1-alpha-20195-1008",
    "node-sass": "^4.11.0",
    "react": "^16.13.1",
    "react-app-polyfill": "^1.0.0",
    "react-dom": "^16.13.1",
    "react-router-dom": "^5.0.0",
    "react-scripts": "3.4.1",
    "whatwg-fetch": "^3.2.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "build-themes": "devextreme build",
    "postinstall": "npm run build-themes"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "devextreme-cli": "1.2.1",
    "devextreme-themebuilder": "20.1-stable"
  }
}
`

**Comment by babich-a** [comment]
@lucasfr2cad Thank you for the report. I reproduced the issue and prepared a [PR with a fix](https://github.com/DevExpress/DevExtreme/pull/14034). We will publish npm packages in a few days.

**Comment by babich-a** [comment]
We have published the `devextreme-themebuilder@20.2.1-alpha-20212-0316` package with the fix. The corresponding versions of `devextreme`, `devextreme-react` were also published.
