### ISSUE TITLE
vue3 support

### ISSUE THREAD

**Issue by softboy99** [DevExpress/devextreme-cli#254]
npx -p devextreme-cli devextreme new vue-app app-name still use v20.1.7 version. Please update

**Comment by babich-a** [comment]
Hi @softboy99 . We'll update DevExtreme CLI with the release of 20.2.4. Unfortunately, the 20.2.3 version has a bug with an authorization form.

**Comment by softboy99** [comment]
Hi,
will you use composation api in your new vue3 based application template or old options api for your 20.2.4?

**Comment by rajjanorkar** [comment]
We need this vue3 support i am waiting...
Please help us.

**Comment by rajjanorkar** [comment]
True i also give it a go and with vue js 3.* version application template does not run. (i have applied necessary upgrade to the code, it just shows me blank home page).

**Comment by LexDX** [comment]
Hi @softboy99, @rajjanorkar 

I'm happy to inform you that we released our Vue 3 template. Now, you can use our CLI to install and try it on your side:

npx -p devextreme-cli devextreme new vue-app app-name --version=3
[Create a DevExtreme Application](https://js.devexpress.com/Documentation/Guide/Vue_Components/Create_a_DevExtreme_Application/)

Should you have further questions, feel free to contact us.

**Comment by gkingston** [comment]
The vue template doesn't seem to work.  When running `npx -p devextreme-cli devextreme new vue-app app-name --version=3` the process fails part way through with error:  preset "__default_vue_3__" not found
