### ISSUE TITLE
Vue 3 template not working

### ISSUE THREAD

**Issue by gkingston** [DevExpress/devextreme-cli#734]
# Bug Report

**Package version:**

    devextreme-cli version: 1.3.0

**Steps to reproduce:**
Run `npx -p devextreme-cli devextreme new vue-app somename --version=3`

**Current behavior:**
Part way through the creation, it will error out with the error:  preset "__default_vue_3__" not found.

**Expected behavior:**
Template works and new app creation finishes

**Comment by gkingston** [comment]
@OlegKipchatov  Thanks for getting to this so quick.   I was able to pull this branch and get the Vue 3 template to work, but did have to remove the double quotes you added in packages/devextreme-cli/src/applications/application.vue.js.  I don't know if this is environment related, but I'm using Ubuntu 20.04 and node 16.14

**Comment by liuchuancong** [comment]
This problem still exists.
```
 Info: You provided more than one argument. The first one will be used as the app's name, the rest are ignored.
 ERROR  preset "Default" not found.

available presets:
Default (Vue 3)
Default (Vue 2)
1
```
