### ISSUE TITLE
vue-app type

### ISSUE THREAD

**Issue by vsantin** [DevExpress/devextreme-cli#75]
Hi guys, 

Looks like the vue-app is not available on version 1.1.0-beta.1 yet how shows the documentation. right?

![image](https://user-images.githubusercontent.com/17271999/56606201-b58e0880-65d3-11e9-8c7f-e9977e05969a.png)

**Comment by dxvladislavvolkov** [comment]
@vsantin hi,
We implemented the vue approach in version 1.1.0-beta.2. Also, you can use tag 'next' to try this feature.
Soon we will update the help command

**Comment by vsantin** [comment]
Hi @dxvladislavvolkov.
Ok, great! The Layout Template looks nice! 

Thanks
