### ISSUE TITLE
Why not use a better argument parser?

### ISSUE THREAD

**Issue by jamesgeorge007** [DevExpress/devextreme-cli#99]
# Feature request

Presently the project makes use of `minimist` arg-parser which serves the purpose. But, IMO using something like `commander.js` makes the code-base much concise. 
Just thoughts :thinking:

**Comment by LexDX** [comment]
Hi @jamesgeorge007,

Thank you for your suggestion. We will consider the commander.js parser in the future, however, I can't give you any ETA.
